# Generated by Django 3.2.23 on 2024-01-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CP', 'Confirmation Pending'), ('C', 'Confirmed'), ('S', 'Shipped'), ('I', 'In Transit'), ('O', 'Out For Delivery'), ('D', 'Delivered')], default='CP', max_length=200, null=True),
        ),
    ]
