# Generated by Django 3.2.23 on 2024-01-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confirmation Pending', 'Confirmation Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], default='CP', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=200, null=True),
        ),
    ]
