# Generated by Django 3.2.23 on 2024-01-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20240116_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confirmation Pending', 'Confirmation Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], default='Confirmation Pending', max_length=200, null=True),
        ),
    ]
